[package]
name = "mqtt-broker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
bytes = "1.9.0"
env_logger = "0.11.5"
hex = "0.4.3"
log = "0.4.22"
tokio = { version = "1", features = ["full"] }
